### PR TITLE
Fix f28 (gcc 8.1) compilation

### PR DESCRIPTION
**Pull request by bdeyal**
Original:
```
nvme.c:1253:48: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
  snprintf(sspath, sizeof(sspath), "%s/subsysnqn", path);
                                                ^
```

### CODE REVIEW

**Comment by bdeyal** [comment]
Verified my change compiles OK with older gcc (RHEL7 gcc 4.8), and clang as well.

**Comment by bdeyal** [comment]
Fixed elsewhere. Closing pull request.
